### ISSUE TITLE
Saucebot doesn't seem to be working at all any more! Any idea what caused the issue?

### ISSUE THREAD

**Issue by HeckinPaw** [JeremyRuhland/saucebot-discord#15]

**Comment by goopypanther** [comment]
Saucebot Twitter has been discontinued due to discord desktop now embedding multi image tweets correctly. (Unfortunately its not on mobile but there's no way to differentiate between clients)

Saucebot FA is currently down due to ongoing DDOS, the API is not official and has no back end support so we have to just wait it out.

**Comment by HeckinPaw** [comment]
I figured that's what was up with the fa links. Connections are just straight up refused. 
What about e621 links? I can't seem to figure out what's up with that.

**Comment by goopypanther** [comment]
e621 links should now be fixed, they apparently have a user agent requirement. I'll have to dig deeper with the FA API since it looks like the site hosting it went down.

**Comment by GigiNik** [comment]
Sorry to bother ya, but any update to when FA links will be working?

**Comment by goopypanther** [comment]
FA function should be restored
